### ISSUE TITLE
Asignacion de Credenciales

### ISSUE THREAD

**Issue by ElLucho74** [ElLucho74/Mario#2]
Profe, podria pasar las credenciales por favor?

**Comment by ingreyeslara** [comment]
Credenciales:
![lucho](https://github.com/ElLucho74/Mario/assets/75334788/65cef8cf-1b69-4464-aa5f-8bfc8231ecc1)
![lucho_2](https://github.com/ElLucho74/Mario/assets/75334788/2e6f20a9-f41f-40fb-8c1f-e7b38a876281)
